// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AIService.proto

package com.demo.proto;

public interface DetectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.DetectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string Id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string shouldStudents = 2;</code>
   */
  java.lang.String getShouldStudents();
  /**
   * <code>string shouldStudents = 2;</code>
   */
  com.google.protobuf.ByteString
      getShouldStudentsBytes();
}
