// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AIService.proto

package com.demo.proto;

public interface DetectReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.DetectReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string actualStudents = 1;</code>
   */
  java.lang.String getActualStudents();
  /**
   * <code>string actualStudents = 1;</code>
   */
  com.google.protobuf.ByteString
      getActualStudentsBytes();
}
