// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AIService.proto

package com.demo.proto;

public final class FaceServiceProto {
  private FaceServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_DetectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_DetectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_DetectReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_DetectReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_RecognizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_RecognizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_RecognizeReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_RecognizeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017AIService.proto\022\007example\"3\n\rDetectRequ" +
      "est\022\n\n\002Id\030\001 \001(\t\022\026\n\016shouldStudents\030\002 \001(\t\"" +
      "%\n\013DetectReply\022\026\n\016actualStudents\030\001 \001(\t\"%" +
      "\n\020RecognizeRequest\022\021\n\tstudentId\030\001 \001(\t\"#\n" +
      "\016RecognizeReply\022\021\n\tencodings\030\001 \001(\t2\213\001\n\004F" +
      "ace\022<\n\nFaceDetect\022\026.example.DetectReques" +
      "t\032\024.example.DetectReply\"\000\022E\n\rFaceRecogni" +
      "ze\022\031.example.RecognizeRequest\032\027.example." +
      "RecognizeReply\"\000B$\n\016com.demo.protoB\020Face" +
      "ServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_example_DetectRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_DetectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_DetectRequest_descriptor,
        new java.lang.String[] { "Id", "ShouldStudents", });
    internal_static_example_DetectReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_DetectReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_DetectReply_descriptor,
        new java.lang.String[] { "ActualStudents", });
    internal_static_example_RecognizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_example_RecognizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_RecognizeRequest_descriptor,
        new java.lang.String[] { "StudentId", });
    internal_static_example_RecognizeReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_example_RecognizeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_RecognizeReply_descriptor,
        new java.lang.String[] { "Encodings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
