// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AIService.proto

package com.demo.proto;

public interface RecognizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.RecognizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentId = 1;</code>
   */
  java.lang.String getStudentId();
  /**
   * <code>string studentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIdBytes();
}
